spring:
  application:
    name: booking-service
  data:
    web:
      pageable:
        default-page-size: 15
        max-page-size: 30
        one-indexed-parameters: true
      sort:
        sort-parameter: sort
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/main-changelog.xml
  config:
    import: 'optional:configserver:'
server:
  port: 8083