server {
    listen 5173;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /auth-api/ {
        proxy_pass http://api-gateway:8089/auth-api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /user-api/ {
        proxy_pass http://api-gateway:8089/user-api/;
        proxy_set_header Host $host;
    }

    location /booking-api/ {
        proxy_pass http://api-gateway:8089/booking-api/;
        proxy_set_header Host $host;
    }

    location /notification-api/ {
        proxy_pass http://api-gateway:8089/notification-api/;
        proxy_set_header Host $host;
    }
}