spring:
  elasticsearch:
    uris: http://localhost:9200
  datasource:
    url: jdbc:h2:mem:booking_db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password: sldgfhergu
  kafka:
    bootstrap-servers: localhost:9093

eureka:
  client:
    enabled: false

minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin123
  hotels-bucket: hotels
  public-url: http://localhost:9000
  rooms-bucket: rooms

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
staynova:
  filters:
    role-header: false
app:
  swagger:
    local-url: http://localhost:8083/booking-api

roles:
  admin-role: ROLE_ADMIN
  user-role: ROLE_USER
