spring:
  liquibase:
    change-log: classpath:db/changelog/main-changelog.xml
  kafka:
    bootstrap-servers: localhost:9093
    consumer:
      auto-offset-reset: latest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

eureka:
  client:
    enabled: false

app:
  swagger:
    local-url: http://localhost:8089/payment-api

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
