spring:
  kafka:
    bootstrap-servers: localhost:9093
  datasource:
    url: jdbc:h2:mem:payment_db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

eureka:
  client:
    enabled: false

app:
  swagger:
    local-url: http://localhost:8085/payment-api

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
