spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: sldgfhergu
  security:
    enabled: false

jwt:
  expiration: 3h
  secret: Tc8Y6p8Rl2A5fK9jBm3QwXrVdSg7ZhNvLcM4HtJqP1eW0aRbF3GyIuOxC5E6Dn

eureka:
  client:
    enabled: false

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs

clients:
  user-service:
    url: http://localhost:8090
staynova:
  filters:
    role-header: false
app:
  swagger:
    local-url: http://localhost:8089/auth-api
