input {
  tcp {
    port  => 5000
    codec => json_lines
  }
}

filter {
  if [mdc][reservationId] {
    mutate {
      add_field => { "reservation_id" => "%{[mdc][reservationId]}" }
    }
  }

  if [mdc][userLogin] {
    mutate {
      add_field => { "user_login" => "%{[mdc][userLogin]}" }
    }
  }
  mutate {
    remove_field => ["@version"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "staynova-logs-%{[service]}-%{+YYYY.MM.dd}"
  }
}
