server:
  port: 8089
spring:
  application:
    name: api-gateway
  config:
    import: 'optional:configserver:'
  main:
    web-application-type: reactive

management:
  endpoints:
    web:
      exposure:
        include: '*'
  prometheus:
    metrics:
      export:
        enabled: true
